nombre: Linters

en: pull_request

env:
  FORCE_COLOR: 1

trabajos:
  faro:
    nombre: Faro
    se ejecuta en: ubuntu-22.04
    pasos:
      - usos: acciones/checkout@v3
      - usos: acciones/setup-node@v3
        con:
          versión de nodo: "18.x"
      - nombre: Configuración del faro
        ejecutar: npm install -g @lhci/cli@0.11.x
      - nombre: Informe del faro
        ejecutar: ejecución automática de lhci --upload.target=almacenamiento público temporal --collect.staticDistDir=.
  sugerencia web:
    nombre: Webhint
    se ejecuta en: ubuntu-22.04
    pasos:
      - usos: acciones/checkout@v3
      - usos: acciones/setup-node@v3
        con:
          versión de nodo: "18.x"
      - nombre: Configurar Webhint
        ejecutar: |
          npm install --save-dev sugerencia@7.x
          [ -f .hintrc ] || wget https://raw.githubusercontent.com/microverseinc/linters-config/master/html-css-js/.hintrc
      - nombre: Informe Webhint
        ejecutar: pista npx.
  estilo:
    nombre: Stylelint
    se ejecuta en: ubuntu-22.04
    pasos:
      - usos: acciones/checkout@v3
      - usos: acciones/setup-node@v3
        con:
          versión de nodo: "18.x"
      - nombre: Configurar Stylelint
        ejecutar: |
          npm install --save-dev stylelint@13.x stylelint-scss@3.x stylelint-config-standard@21.x stylelint-csstree-validator@1.x
          [ -f .stylelintrc.json ] || wget https://raw.githubusercontent.com/microverseinc/linters-config/master/html-css-js/.stylelintrc.json
      - nombre: Informe Stylelint
        ejecutar: npx stylelint "**/*.{css,scss}"
  eslint:
    nombre: ESLint
    se ejecuta en: ubuntu-22.04
    pasos:
      - usos: acciones/checkout@v3
      - usos: acciones/setup-node@v3
        con:
          versión de nodo: "18.x"
      - nombre: Configurar ESLint
        ejecutar: |
          npm install --save-dev eslint@7.x eslint-config-airbnb-base@14.x eslint-plugin-import@2.x babel-eslint@10.x
          [ -f .eslintrc.json ] || wget https://raw.githubusercontent.com/microverseinc/linters-config/master/html-css-js/.eslintrc.json
      - nombre: Informe ESLint
        ejecutar: npx eslint.
  verificador de nodos:
    nombre: comprobador de node_modules
    se ejecuta en: ubuntu-22.04
    pasos:
      - usos: acciones/checkout@v3
      - nombre: comprobar la existencia de node_modules
        ejecutar: |
          if [ -d "node_modules/" ]; luego echo -e "\e[1;31mLa carpeta node_modules/ fue enviada al repositorio. Elimínela del repositorio de GitHub y vuelva a intentarlo."; echo -e "\e[1;32mPuede configurar un archivo .gitignore con esta carpeta incluida para evitar que esto suceda en el futuro". && salida 1; fi